// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const CartItems = sequelize.define('cartItems', {
    status: {
      type: DataTypes.STRING,
    },
    quantity: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    price: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'cart_items',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  CartItems.associate = (models) => {
    CartItems.belongsTo(models.items, {
      foreignKey: {
        name: 'itemIdKey',
        field: 'item_id',
      },
      as: 'item',
    });
    CartItems.belongsTo(models.carts, {
      foreignKey: {
        name: 'cartIdKey',
        field: 'cart_id',
      },
      as: 'cart',
    });
  };

  return CartItems;
};
