// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Clientes = sequelize.define('clientes', {
    name: {
      type: DataTypes.STRING,
    },
    razonSocial: {
      type: DataTypes.STRING,
    },
    tel: {
      type: DataTypes.STRING,
    },
    email: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    ruc: {
      type: DataTypes.STRING,
    },
    date: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'clientes',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Clientes.associate = (models) => {
    Clientes.hasMany(models.ubicacions, {
      foreignKey: {
        name: 'clienteIdKey',
        field: 'cliente_id',
      },
      as: 'ubicacions',
    });
    Clientes.hasMany(models.carts, {
      foreignKey: {
        name: 'clienteIdKey',
        field: 'cliente_id',
      },
      as: 'carts',
    });
    Clientes.hasMany(models.facturas, {
      foreignKey: {
        name: 'clienteIdKey',
        field: 'cliente_id',
      },
      as: 'facturas',
    });
  };

  return Clientes;
};
