// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Facturas = sequelize.define('facturas', {
    nro: {
      type: DataTypes.STRING,
    },
    razonSocial: {
      type: DataTypes.STRING,
    },
    ruc: {
      type: DataTypes.STRING,
    },
    email: {
      type: DataTypes.STRING,
    },
    condicion: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    total: {
      type: DataTypes.INTEGER,
    },
    date: {
      type: DataTypes.DATE,
    },
    pagado: {
      type: DataTypes.INTEGER,
    },
    saldo: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'facturas',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Facturas.associate = (models) => {
    Facturas.belongsTo(models.carts, {
      foreignKey: {
        name: 'cartIdKey',
        field: 'cart_id',
      },
      as: 'cart',
    });
    Facturas.belongsTo(models.clientes, {
      foreignKey: {
        name: 'clienteIdKey',
        field: 'cliente_id',
      },
      as: 'cliente',
    });
    Facturas.belongsTo(models.users, {
      foreignKey: {
        name: 'userIdKey',
        field: 'user_id',
      },
      as: 'user',
    });
    Facturas.hasMany(models.movItems, {
      foreignKey: {
        name: 'facturaIdKey',
        field: 'factura_id',
      },
      as: 'movItems',
    });
  };

  return Facturas;
};
