// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Items = sequelize.define('items', {
    name: {
      type: DataTypes.STRING,
    },
    description: {
      type: DataTypes.STRING,
    },
    costPrice: {
      type: DataTypes.INTEGER,
    },
    salesPrices: {
      type: DataTypes.INTEGER,
    },
    stock: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'items',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Items.associate = (models) => {
    Items.hasMany(models.movItems, {
      foreignKey: {
        name: 'itemIdKey',
        field: 'item_id',
      },
      as: 'movItems',
    });
    Items.hasMany(models.cartItems, {
      foreignKey: {
        name: 'itemIdKey',
        field: 'item_id',
      },
      as: 'cartItems',
    });
  };

  return Items;
};
