version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: megachopp
    environment:
      - APPLICATION_PORT=3310
      - DATABASE_URL=postgres://RUBENMEDINA:megachopp_cuarentena@host.docker.internal:5432/megachopp_cuarentena_development
      - DATABASE_SCHEMA=public
      - DATABASE_SSL=false
      - FOREST_AUTH_SECRET=0a93b02481bed6c243841ae2a0114607e5c3265af5ad12f3a305bef2ce0ae6374cca6980a5f6bc441a8292ed4f8b3356
      - FOREST_ENV_SECRET=159a0edb027db650a8fd1936ab6cbe6478819383e57d8a2040b3d864867ee8c8
    ports:
      - "3310:3310"
    volumes:
      - ./:/usr/src/app
